name: shellcheck
on:
  push:
    branches: []
  schedule:
    - cron: "5 19 * * 1"
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install shellcheck'
        run: |
         sudo apt-get update
         sudo apt-get install -y shellcheck
      - name: 'Check pre-deploy script'
        run: |
         shellcheck pre_deploy.sh
         if [ $? -eq 0 ]; then echo "exit "$?": Shellcheck completed. No issues found."; fi
