name: actions_events
on:
  push:
    branches: [ envvar ]
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set pipeline-run output
        id: set-pipeline-run
        run: |
          OPEN_PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.TEST_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository }}:envvar" | jq '. | length')
          echo "Open pr count is: $OPEN_PR_COUNT"
          if [ "$OPEN_PR_COUNT" -eq "0" ]; then
            echo "pipeline-run=true" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          else
            echo "pipeline-run=false" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          fi
    outputs:
      pipeline-run: ${{ steps.set-pipeline-run.outputs.pipeline-run }}

  run-tests:
    needs: check-pr
    if: ${{ needs.check-pr.outputs.pipeline-run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Test 3"
