name: actions_events
on:
  push:
    branches: [ envvar ]
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open pull requests
        id: check_pr
        run: |
          OPEN_PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.TEST_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository }}:main" | jq '. | length')
          echo "open_pr_count=$OPEN_PR_COUNT" >> "$GITHUB_ENV"
          echo "Open pr count is: $OPEN_PR_COUNT"
          echo "GitHub env is: $GITHUB_ENV"

      - name: Set pipeline_run output
        id: set_pipeline_run
        run: |
          if [ "$OPEN_PR_COUNT" -eq "0" ]; then
            echo "{pipeline_run}={true}" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          else
            echo "{pipeline_run}={false}" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          fi
        env:
          OPEN_PR_COUNT: ${{ env.open_pr_count }}

  run-tests:
    needs: check-pr
    if: ${{ needs.check-pr.outputs.pipeline_run == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Open PR count is $GITHUB_ENV and it's set value is $GITHUB_OUTPUT."
