name: actions_events
on:
  push:
    branches: [ envvar ]
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set pipeline-run output
        id: set-pipeline-run
        run: |
          OPEN_PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.TEST_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | grep '\"state\"\: \"open\"' | wc -l)
          echo "$OPEN_PR_COUNT"
          if [ "$OPEN_PR_COUNT" -eq "0" ]; then
            echo "open-pr=false" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          else
            echo "open-pr=true" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          fi
    outputs:
      open-pr: ${{ steps.set-pipeline-run.outputs.open-pr }}

  run-tests:
    needs: check-pr
    if: ${{ (needs.check-pr.outputs.open-pr == 'false') && (github.event_name == 'push') && (github.ref != '') && (github.event.release.tag_name == '') }}
## github.ref has to be tested with tag to see ig it gets triggered!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Variable values: openpr: ${{ needs.check-pr.outputs.open-pr }} , event name: ${{ github.event_name }} , ref: ${{ github.ref }} , tag name: ${{ github.event.release.tag_name }} ."
