name: actions_events
on:
  push:
    branches: [ envvar ]
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set pipeline-run output
        id: set-pipeline-run
        run: |
          OPEN_PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.TEST_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | grep '\"state\"\: \"open\"' | wc -l)
          if [ "$OPEN_PR_COUNT" -eq "0" ]; then
            echo "open-pr=false" >> "$GITHUB_OUTPUT"
          else
            echo "open-pr=true" >> "$GITHUB_OUTPUT"
          fi
    outputs:
      open-pr: ${{ steps.set-pipeline-run.outputs.open-pr }}

  run-tests:
    needs: check-pr
    if: ${{ github.ref }} && ${{ github.event_name }} == "push" && ${{ needs.check-pr.outputs.open-pr == "false" }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Test"
