name: actions_events
on:
  push:
    branches: [ envvar ]
#    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set open-pr output
        id: set-open-pr
        run: |
          OPEN_PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.TEST_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | grep '\"state\"\: \"open\"' | wc -l)
          echo "$OPEN_PR_COUNT"
          if [ "$OPEN_PR_COUNT" -eq "0" ]; then
            echo "open-pr=false" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          else
            echo "open-pr=true" >> "$GITHUB_OUTPUT"
            ECHO_OUTPUT=$(cat $GITHUB_OUTPUT) && echo "GitHub output is: $ECHO_OUTPUT"
          fi

      - name: Set regex-match output
        id: set-regex-match
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "regex-match=true" >> "$GITHUB_OUTPUT"
          fi
    outputs:
      open-pr: ${{ steps.set-pipeline-run.outputs.open-pr }}
      regex-match: ${{ steps.set-regex-match.outputs.regex-match }}

  run-test-if-one:
    needs: check-pr
#    if: ${{ (needs.check-pr.outputs.open-pr == 'false') && (github.event_name == 'push') && (github.ref_type == 'branch') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find node
        run: |
          FIND_PATH=$(ls -la / | grep -v proc | grep -v tmp | grep -v dev | grep -v sys | grep -v mnt | grep -v boot | sed 1,3d | awk -F' ' '{print $9}')
          node -v
          whereis node
          for path in $FIND_PATH; do find /$path -name node; done

      - name: Run tests
        run: |
          echo "Variable values: openpr: ${{ needs.check-pr.outputs.open-pr }} , event name: ${{ github.event_name }} , ref: ${{ github.ref }} , ref type: ${{ github.ref_type }} ."

  run-test-if-two:
    needs: check-pr
    if: ${{ (needs.check-pr.outputs.regex-match == 'true') && (github.event_name == 'push') && (github.ref_type == 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Variable values: openpr: ${{ needs.check-pr.outputs.regex-match }} , event name: ${{ github.event_name }} , ref: ${{ github.ref }} , ref type: ${{ github.ref_type }} ."
