name: sdk_test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java Environment
        run: |
         curl -s "https://get.sdkman.io" | bash
         bash -c "source $HOME/.sdkman/bin/sdkman-init.sh"
         sdk install java 11.0.16-zulu
         sdk install gradle 7.4
         sdk version
         sdk help
         whereis sdk
         sudo find / -name sdk
         sudo find / -name java
         echo $SDKMAN_DIR
         echo $JAVA_HOME
